"""
Replace the three embedded PNGs in
papers/p3-singapore/Manuscript_Blinded_MIR_2_revised.docx with the
manuscript-ready figures generated by 70_make_figures_for_manuscript.py.

Mapping (verified against document.xml.rels and figure captions):
  word/media/image3.png  ←  outputs/r3/figures/Fig1_conceptual.png    (Figure 1)
  word/media/image2.png  ←  outputs/r3/figures/Fig2_DAI_marginal.png  (Figure 2)
  word/media/image1.png  ←  outputs/r3/figures/Fig3_IP_predicted.png  (Figure 3)

A docx is a zip; we rebuild it byte-for-byte except for the three image
entries which are swapped to the new PNG bytes.
"""
from pathlib import Path
import shutil
import zipfile

REPO = Path(__file__).resolve().parents[2]
DOC = REPO / "papers" / "p3-singapore" / "Manuscript_Blinded_MIR_2_revised.docx"
FIG_DIR = REPO / "outputs" / "r3" / "figures"
BACKUP = REPO / "papers" / "p3-singapore" / "Manuscript_Blinded_MIR_2_revised.before-figs.docx"

REPLACEMENTS = {
    "word/media/image3.png": FIG_DIR / "Fig1_conceptual.png",     # Fig 1
    "word/media/image2.png": FIG_DIR / "Fig2_DAI_marginal.png",   # Fig 2
    "word/media/image1.png": FIG_DIR / "Fig3_IP_predicted.png",   # Fig 3
}


def main():
    print("=" * 72)
    print("Embed 3 manuscript-ready figures into the docx")
    print("=" * 72)

    if not BACKUP.exists():
        shutil.copy(DOC, BACKUP)
        print(f"Backup created: {BACKUP}")

    # Read all entries from the original docx
    with zipfile.ZipFile(DOC, "r") as z_in:
        entries = {n: z_in.read(n) for n in z_in.namelist()}

    print(f"\nOriginal docx: {len(entries)} entries.")

    # Replace the three image entries
    for member, src in REPLACEMENTS.items():
        if member not in entries:
            raise SystemExit(f"Member {member} not in docx — abort.")
        if not src.exists():
            raise SystemExit(f"Source figure {src} missing — abort.")
        old_bytes = entries[member]
        new_bytes = src.read_bytes()
        entries[member] = new_bytes
        print(f"  Replaced {member}: "
              f"{len(old_bytes):,} → {len(new_bytes):,} bytes  (← {src.name})")

    # Rewrite docx
    with zipfile.ZipFile(DOC, "w", zipfile.ZIP_DEFLATED) as z_out:
        for name, data in entries.items():
            z_out.writestr(name, data)
    print(f"\nWrote: {DOC}")

    # Verify by re-reading the 3 images out
    with zipfile.ZipFile(DOC, "r") as z:
        for member, src in REPLACEMENTS.items():
            stored = z.read(member)
            if stored != src.read_bytes():
                raise SystemExit(f"VERIFICATION FAIL: {member} bytes differ "
                                 f"from source {src}")
            print(f"  ✓ {member} matches {src.name} ({len(stored):,} bytes)")

    print("\nAll 3 figures embedded successfully.")


if __name__ == "__main__":
    main()
