#!/bin/bash
# P4 Vietnam — Bootstrap script to fetch binary submission files from source branch
#
# Usage (after cloning thesis branch):
#   cd papers/p4-vietnam/
#   bash bootstrap.sh
#
# Downloads:
# - 4 manuscript DOCX files (blinded + with-authors, v5.8 baseline + v5.9 final)
# - 1 cover letter DOCX
# - 1 response letter DOCX (round 2)
# - 7 figure PNG + 7 PDF
# - 6 figure source XLSX
# - 1 SUBMISSION_CHECKLIST.md
#
# All from claude/update-p4-draft-W6UKL branch raw URLs.

set -euo pipefail
cd "$(dirname "$0")"

BASE="https://raw.githubusercontent.com/huongctu/Class-AI-Agent/claude/update-p4-draft-W6UKL/submission"

mkdir -p manuscript submission figures figures/source

echo "[1/4] Downloading manuscript files..."
curl -fsSL -o manuscript/manuscript_blinded_v5_8.docx "${BASE}/manuscript_blinded.docx" || echo "  (legacy v5.8 not on source branch — skipped)"
curl -fsSL -o manuscript/manuscript_full_with_authors_v5_8.docx "${BASE}/manuscript_full_with_authors.docx" || echo "  (legacy v5.8 not on source — skipped)"

echo "  Note: v5.9 final files are generated by running replication/apply_v59_edits.py"
echo "  See replication/README.md Step 2 for detailed instructions"

echo "[2/4] Downloading submission letters + checklist..."
curl -fsSL -o submission/cover_letter_ijoem.docx "${BASE}/cover_letter_ijoem.docx"
curl -fsSL -o submission/response_letter_round2.docx "${BASE}/response_letter_round2.docx"
curl -fsSL -o submission/SUBMISSION_CHECKLIST.md "${BASE}/SUBMISSION_CHECKLIST.md" || true
curl -fsSL -o submission/README.md "${BASE}/README.md" || true

echo "[3/4] Downloading figures (PNG + PDF)..."
for f in figure_1_conceptual_model figure_2a figure_2b figure_2c figure_2d figure_2_main_results figure_3_moderator_marginals; do
  curl -fsSL -o "figures/${f}.png" "${BASE}/figures/${f}.png" || echo "  (${f}.png unavailable)"
  curl -fsSL -o "figures/${f}.pdf" "${BASE}/figures/${f}.pdf" || echo "  (${f}.pdf unavailable)"
done

echo "[4/4] Downloading figure source XLSX (data + chart + embedded image)..."
for f in figure_1_conceptual_model figure_2a figure_2b figure_2c figure_2d figure_3_moderator_marginals; do
  curl -fsSL -o "figures/source/${f}.xlsx" "${BASE}/figures_excel/${f}.xlsx" || echo "  (${f}.xlsx unavailable)"
done

echo ""
echo "✓ Bootstrap complete."
echo ""
echo "Next steps:"
echo "  1. Apply 20 v5.9 edits: python3 replication/apply_v59_edits.py"
echo "  2. Submission package ready in manuscript/ + submission/ + figures/"
echo ""
echo "For IJoEM upload, use:"
echo "  - manuscript/manuscript_v5_9_blinded.docx → Main document"
echo "  - manuscript/manuscript_v5_9_full_with_authors.docx → Title page"
echo "  - submission/cover_letter_ijoem.docx → Cover letter"
echo "  - submission/response_letter_round2.docx → Response to reviewers"
echo "  - figures/*.pdf or *.png → Figure files"
